pipeline {
    agent any
    parameters {
        string(defaultValue: "Test", description: "Which environment to deploy in?", name: "deployEnv")
    }
    stages {
        stage("User input demo"){
            steps {
                echo "Environment is set to ${params.deployEnv}"
            }
        }
    }
}